### ISSUE TITLE
pipeline should send failed test result if can't build scratch build for PRs

### ISSUE THREAD

**Issue by bgoncalv** [fedora-ci/dist-git-pipeline#20]
For PR the pipeline will try to build an scratch build, but if any step there fails, the pipeline doesn't send any result.

https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-build-pipeline

ex: https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-build-pipeline

**Comment by msrb** [comment]
I think this issue has been resolved already. Closing ;)
